"""initial

Revision ID: a4c76d1d300f
Revises: 
Create Date: 2026-07-21 23:49:07.176889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4c76d1d300f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_entries',
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('object_key', sa.String(length=1024), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'failed', name='processingstatus', native_enum=False), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_entries')),
    sa.UniqueConstraint('object_key', name=op.f('uq_knowledge_entries_object_key'))
    )
    op.create_index(op.f('ix_knowledge_entries_sha256'), 'knowledge_entries', ['sha256'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_status'), 'knowledge_entries', ['status'], unique=False)
    op.create_index('ix_knowledge_status_deleted', 'knowledge_entries', ['status', 'deleted_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_last_activity_at'), 'users', ['last_activity_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=100), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_id_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index('ix_sessions_user_deleted', 'sessions', ['user_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('user', 'assistant', name='messagerole', native_enum=False), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='messagestatus', native_enum=False), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_chat_messages_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages')),
    sa.UniqueConstraint('session_id', 'sequence_number', name=op.f('uq_chat_messages_session_id'))
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index('ix_chat_messages_session_sequence', 'chat_messages', ['session_id', 'sequence_number'], unique=False)
    op.create_table('uploads',
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('object_key', sa.String(length=1024), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.Enum('pdf', 'image', name='uploadkind', native_enum=False), nullable=True),
    sa.Column('processing_status', sa.Enum('pending', 'processing', 'ready', 'failed', name='processingstatus', native_enum=False), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_uploads_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads')),
    sa.UniqueConstraint('object_key', name=op.f('uq_uploads_object_key'))
    )
    op.create_index('ix_uploads_session_deleted', 'uploads', ['session_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_uploads_session_id'), 'uploads', ['session_id'], unique=False)
    op.create_index(op.f('ix_uploads_sha256'), 'uploads', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_sha256'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_session_id'), table_name='uploads')
    op.drop_index('ix_uploads_session_deleted', table_name='uploads')
    op.drop_table('uploads')
    op.drop_index('ix_chat_messages_session_sequence', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_user_deleted', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_last_activity_at'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_knowledge_status_deleted', table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_status'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_sha256'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    # ### end Alembic commands ###
