class ServiceError(Exception):
    """Base error raised by application services."""


class AuthenticationError(ServiceError): ...
class ConflictError(ServiceError): ...
class InactiveUserError(AuthenticationError): ...
class TokenError(AuthenticationError): ...
class NotFoundError(ServiceError): ...
class InvalidInputError(ServiceError): ...
class ExternalServiceError(ServiceError): ...
